# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7fc221ccb5acaa8294c4b7af62cd73386d9a77769c39930e0312c5ab40b5c012cb6b6c8f6bbf5ff47f943237cb11520e7f4fa6ae403033f54c8d8d585a81073

test:
  secret_key_base: 75991c63fe15928c5611781a6ecf05c8b5ce701903cb65144afb95105f1d67b26c8d04e7d2d106b262ed166ebc1e0a86581445f26c9528256572700884b6a9da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
